exercism/delphi

docs/INSTALLATION.md
First crack at an installation.md file.  Its a start.
=> Initial Installation.md

exercises/clock/ClockTest.dpr, exercises/clock/ClockTest.dproj, exercises/clock/uClockExample.pas, exercises/clock/uClockTest.pas
=> Exercise: clock

exercises/binary-search/BinarySearchTest.dpr, exercises/binary-search/BinarySearchTest.dproj, exercises/binary-search/uBinarySearchExample.pas, exercises/binary-search/uBinarySearchTest.pas
=> Exercise: binary-search

exercises/etl/ETLtests.dpr, exercises/etl/ETLtests.dproj, exercises/etl/uETLexample.pas, exercises/etl/uETLtests.pas
=> ETL Exercise

exercises/nucleotide-count/NucleotideCountTest.dpr, exercises/nucleotide-count/NucleotideCountTest.dproj, exercises/nucleotide-count/uNucleotideCountExample.pas, exercises/nucleotide-count/uNucleotideCountTest.pas
=> Exercise: nucleotide-count

exercises/perfect-numbers/PerfectNumbersTest.dpr, exercises/perfect-numbers/PerfectNumbersTest.dproj, exercises/perfect-numbers/uPerfectNumbersExample.pas, exercises/perfect-numbers/uPerfectNumbersTest.pas
=> Exercise perfect-numbers

.gitignore, exercises/allergies/AllergyTests.dpr, exercises/bank-account/BankAccountTests.dpr, exercises/beer-song/BeerSongTests.dpr, exercises/binary-search/BinarySearchTest.dpr, exercises/bob/BobTests.dpr, exercises/book-store/BookStoreTests.dpr, exercises/bowling/BowlingTests.dpr, exercises/circular-buffer/CircularBufferTests.dpr, exercises/clock/ClockTest.dpr, exercises/etl/ETLtests.dpr, exercises/hamming/Hamming.dpr, exercises/hello-world/TestHelloWorld.dpr, exercises/leap/LeapTest.dpr, exercises/nucleotide-count/NucleotideCountTest.dpr, exercises/perfect-numbers/PerfectNumbersTest.dpr, exercises/phone-number/PhoneNumberTests.dpr
DPRs will be needed if student is using Delphi Starter Edition.
=> restored DPRs

config.json, exercises/saddle-points/TestSaddlePoints.dpr, exercises/saddle-points/uSaddlePointsExample.pas, exercises/saddle-points/uSaddlePointsTests.pas
=> Exercise: saddle-points

config.json
Changed language name to Object Pascal.
=> Config json

exercises/nucleotide-count/uNucleotideCountExample.pas, exercises/nucleotide-count/uNucleotideCountTest.pas
To simplify the solution I have removed the need of an abstraction (interface) layer to the class the students will be creating.
=> [nucleotide-count] Update removes abstraction layer

docs/INSTALLATION.md
=> Update installation document for Delphi

config.json
=> Slug and repository configuration to Delphi

SETUP.md
=> Fix references in Setup.md

exercises/hello-world/uHelloWorldExample.pas, exercises/hello-world/uTestHelloWorld.pas
Removed the requirement that the student create a class.  A simple function is all that is asked for.
=> hello-world: updated to conform better with description.md

docs/RESOURCES.md
I had a lot more content in a version prior to this commit, but I found that the main url I was referencing didn't work reliably, so that content was cut.  I would like to find more content.  Stuff out there from Nick Hodges, Boian Mitov, or Marco Cantu should be looked into.
=> resources.md

config.json
assigned a difficulty level of 1.
=> adds exercise rna-transcription

exercises/hello-world/uHelloWorldExample.pas, exercises/hello-world/uTestHelloWorld.pas
Exercise has been simplified in accordance with documentation recently released in x-common for this exercise.  This exercise is now only intended to help the student realize that they have properly installed the tools required for a particualr track and that they are working correctly.
=> hello-world: update exercise to agree with canonical-data.json

config.json, exercises/poker/Poker.dpr, exercises/poker/uPokerExample.pas, exercises/poker/uPokerTest.pas
based on C# version of exercise.
=> poker: added exercise to this track

exercises/bowling/uBowlingExample.pas, exercises/bowling/uBowlingTests.pas
Updated tests and example to closely follow recently updated canonical-data.json.
=> bowling: update to align to canonical-data.json

exercises/allergies/uAllergyTests.pas, exercises/bank-account/uBankAccountTests.pas, exercises/beer-song/uBeerSongTests.pas, exercises/binary-search/uBinarySearchTest.pas, exercises/bob/uBobTests.pas, exercises/book-store/uBookStoreTests.pas, exercises/bowling/uBowlingTests.pas, exercises/circular-buffer/uCircularBufferTests.pas, exercises/clock/uClockTest.pas, exercises/etl/uETLtests.pas, exercises/grains/uGrainsTests.pas, exercises/hamming/uHammingTests.pas, exercises/leap/uLeapTests.pas, exercises/nucleotide-count/uNucleotideCountTest.pas, exercises/perfect-numbers/uPerfectNumbersTest.pas, exercises/phone-number/uPhoneNumberTests.pas, exercises/poker/uPokerTest.pas, exercises/rna-transcription/uTestRnaTranscription.pas, exercises/saddle-points/uSaddlePointsTests.pas
A blurb has been added to all [Ignore] markers to remind the student to comment those lines to activate that particular test.
=> brings uniformity to all [Ignore] markers in all exercises

config.json, exercises/triangle/Triangle.dpr, exercises/triangle/uTestTriangle.pas, exercises/triangle/uTriangleExample.pas
=> Triangle: adding new exercise

SETUP.md
This information is delivered with the readme.md that is provided with each fetched exercise.  This file will now inform the student how to load the exercise into Delphi, how to compile/run the exercise/project, and where they can find support on gitter for when they have questions.
=> setup.md: adds information on operating delphi and for seeking help

docs/TESTS.md
Intent is to inform student what files they should be looking for and to be sure to review the readme.md that is delivered via the fetch.
=> tests.md: inserts instructions on what files are delivered via fetch

exercises/hello-world/uTestHelloWorld.pas
The information at the top of the file feels kludgy to me, but I am not sure how to spruce it up.
=> hello-world: inserts sample solution at top of test runner

exercises/clock/uClockExample.pas, exercises/clock/uClockTest.pas
Many new tests were added and a few dropped.  Example solution also updated.
=> clock: update to match new canonical-data.json

exercises/allergies/uAllergiesExample.pas
=> Allergies: update example to remove memory leak

exercises/hello-world/uTestHelloWorld.pas
Being the first exercise I thought it important to illustrate for the student what are the params of Assert.AreEqual.
=> hello-world: update to ease comprehension

exercises/bowling/uBowlingTests.pas
Several instances of 'can_not' replaced with 'cannot'.
=> bowling: Update to version 1.0.1

docs/TESTS.md
This is mostly here to check the appveyor settings, but may be a good change anyway.
=> Reference cli by general name

config/maintainers.json
=> rpottsoh: show_on_website => true

config/maintainers.json
Hi @rpottsoh, just noticed a little typo in the maintainers.json when I was importing track metadata into the nextercism database :)
=> Fixed syntax typo in maintainers.json

docs/SNIPPET.txt
Just used example hello-world solution.  I may want to contrive something original later, that isn't associated to any problem/solution.
=> Code Snippet for Nextercism

exercises/hamming/uHammingExample.pas, exercises/hamming/uHammingTests.pas
Exception messages were updated in the recent update to the canonical-data.json file.
=> Hamming: Update to align with recent update to canonical data

config/maintainers.json
Mainly want to see how quickly this update hits the new site.
=> update Ryan BIO

docs/SNIPPET.txt
This example is not Hello-World like most are using.  This code also is not directly related to any exercises, that I am aware of.  It is also cool because it features recursion...
=> a more generic snippet of code

exercises/circular-buffer/README.md
Ran configlet generate which caused this readme to be updated.  This exercise was recently updated in exercism/problem-specifications.
=> circular-buffer: Update README.md

config/maintainers.json
executed configlet fmt against repo and this is what resulted.  Everything appears to be alphabetized.
=> maintainers.json: updated via configlet

config.json
configlet fmt alphabetized everything.  This puts the track title at the bottom of the file.  Not sure I like that.  I also ran configlet lint against the track.  It complained that all the UUIDs were not unique.  I created a batch file to generate enough UUIDs for each track in this repo and applied each one to each exercise declared in this JSON file.
=> config.json: updated by configlet fmt

config.json, exercises/pig-latin/PigLatin.dpr, exercises/pig-latin/README.md, exercises/pig-latin/uPigLatinExample.pas, exercises/pig-latin/uTestPigLatin.pas
=> pig-latin: New Exercise

exercises/pig-latin/uPigLatinExample.pas
C# track was my inspiration for this update.  Their solution to the rhythm test was better than mine.  Thanks!
=> pig-latin: Simplified example solution

exercises/leap/uLeapTests.pas
tests now match canonical-data.json
=> leap: update tests to align with test data

exercises/hamming/uHammingTests.pas
update to agree with changes made to two tests.
=> hamming: update to align with test data

exercises/nucleotide-count/uNucleotideCountTest.pas
ordering of two tests was swapped.....
=> nucleotide-count: update to agree with test data

exercises/leap/uLeapTests.pas
based on PR exercism/problem-specifications#971
=> leap: update test

exercises/two-fer/README.md
Description.md recently updated.....
=> two-fer: Update README.md

exercises/phone-number/README.md
Description.md recently updated.
=> phone-number: update README

exercises/book-store/uBookStoreExample.pas, exercises/book-store/uBookStoreTests.pas
Test Suite and example solution updated per changes added in exercism/problem-specifications#1021
=> book-store: Update to v1.1.0

exercises/armstrong-numbers/uArmstrongNumbersExample.pas
I liked the proposed Java solution to this exercise more than the one I implemented.
=> Armstrong-Numbers: Update Example

exercises/book-store/uBookStoreExample.pas, exercises/book-store/uBookStoreTests.pas
Updated per exercism/problem-specifications#1089
=> Book-Store: convert from dollars to cents

exercises/phone-number/uPhoneNumberTests.pas
per exercism/problem-specifications#1090 and exercism/problem-specifications#1120
=> phone-number: update to 1.4.0

exercises/clock/uClockExample.pas, exercises/clock/uClockTest.pas
per exercism/problem-specifications#1145
=> clock: Sync with testdata v2.2.1

exercises/roman-numerals/uRomanNumeralsTest.pas
per exercism/problem-specifications#1139
=> roman-numerals: sync to new testdata v1.2.0

exercises/collatz-conjecture/uCollatzconjectureTest.pas, exercises/hamming/uHammingTests.pas, exercises/hello-world/uTestHelloWorld.pas, exercises/leap/uLeapTests.pas, exercises/minesweeper/uMineSweeperTest.pas, exercises/raindrops/uRaindropsTest.pas, exercises/triangle/uTestTriangle.pas, exercises/two-fer/utwoferTest.pas, exercises/wordy/uWordyTests.pas
CanonicalVersion is a const towards the beginning og the test suite unit.
=> Add CanonicalVersion to test suite

exercises/pig-latin/README.md
update README to be in accordance with exercism/problem-specifications#1171.
=> pig-latin: update README

exercises/isbn-verifier/uTestISBNVerifier.pas
per exercism/problem-specifications#1217
=> isbn-verifier: update to 2.3.0

exercises/bracket-push/uBracketPushTest.pas
add test `partially paired brackets` per exercism/problem-specifications#1219
=> bracket-push: update to 1.3.0

config.json, exercises/grade-school/GradeSchool.dpr, exercises/grade-school/README.md, exercises/grade-school/uGradeSchoolExample.pas, exercises/grade-school/uGradeSchoolTest.pas
add exercise based on implementation found in C# track.
=> grade-school: new exercise

config.json, config/maintainers.json
changes created by 3.9.1 configlet fmt
=> update JSON configurations

config.json
=> hello-world: add "auto_approve": true,

config.json, exercises/word-count/README.md, exercises/word-count/WordCount.dpr, exercises/word-count/uWordCountExample.pas, exercises/word-count/uWordCountTests.pas
=> Word-count : new exercise

exercises/isbn-verifier/uTestISBNVerifier.pas
per exercism/problem-specifications#1255
=> isbn-verifier: update to 2.7.0

exercises/isogram/uIsogramTests.pas
per exercism/problem-specifications#1261
=> update isogram to 1.4.0

exercises/bob/README.md
per exercism/problem-specification#1267
=> update Bob README

docs/TESTS.md
fixes exercism/exercism.io#4024
=> Implement correct url to CLI instructions

config.json, exercises/difference-of-squares/DifferenceOfSquares.dpr, exercises/difference-of-squares/README.md, exercises/difference-of-squares/uDifferenceOfSquaresExample.pas, exercises/difference-of-squares/uDifferenceOfSquaresTests.pas
baseline, empty files.  Tests may be added in and an example written.  Later config.json will be updated alongs with a README generated via Configlet.
=> Difference-of-Squares: new exercise

exercises/saddle-points/GETTING_STARTED_GUIDE.md, exercises/saddle-points/uSaddlePointsTests.pas
closes #249
Also added GETTING_STARTED_GUIDE.md that has been referred to in the comment block of the test suite, but was never included until now....
=> saddle-points: update to v1.2.0

exercises/rna-transcription/uTestRnaTranscription.pas
=> rna-transcription: update to 1.3.0

docs/INSTALLATION.md
Attempting to follow instructions @ https://github.com/exercism/docs/blob/master/language-tracks/documentation/for-consumers.md to fix broken links....
=> fix broken links to images

config/exercise_readme.go.tmpl
A way to work around exercism/exercism#4076
=> Rewrite Incomplete Solutions statement

docs/INSTALLATION.md
remove references to Starter Edition.
=> add references to Community Edition 

exercises/bob/uBobTests.pas
per exercism/problem-specifications#1293
=> bob: update to 1.3.0

config.json, exercises/anagram/Anagram.dpr, exercises/anagram/README.md, exercises/anagram/uAnagramExample.pas, exercises/anagram/uAnagramTests.pas
waiting on exercism/problem-specifications#1301 to be merged.
=> anagram: new exercise

exercises/bracket-push/uBracketPushTest.pas
per exercism/problem-specifications#1300
=> bracket-push: update to v1.4.0

exercises/isogram/uIsogramExample.pas, exercises/isogram/uIsogramTests.pas
adds alphAbet test
refactor example solution
=> isogram: update to v1.5.0

exercises/isogram/uIsogramTests.pas
per exercism/problem-specifications#1308
=> Isogram: update to v1.6.0

exercises/bob/uBobTests.pas
per exercism/problem-specifications#1319
=> Bob: update to v1.4.0

exercises/book-store/uBookStoreExample.pas, exercises/book-store/uBookStoreTests.pas
Thanks to one of my students, Eferim, for coming up with a working solution that passes all the tests for this new version of the exercise.
per exercism/problem-specifications#1297
=> Book-Store: update to v1.4.0

exercises/phone-number/uPhoneNumberTests.pas
per exercism/problem-specifications#1327
=> phone-number: update to v1.5.0

exercises/binary-search/uBinarySearchTest.pas
per exercism/problem-specifications#1338
=> binary-search: bump version to 1.2.0

config.json, exercises/matrix/Matrix.dpr, exercises/matrix/README.md, exercises/matrix/uMatrixExample.pas, exercises/matrix/uMatrixTest.pas
Readme added after numerous fries and fails
=> Matrix: add new exercise to delphi track

config.json, exercises/ocr-numbers/OcrNumbers.dpr, exercises/ocr-numbers/README.md, exercises/ocr-numbers/uOcrNumbers.pas, exercises/ocr-numbers/uOcrNumbersExample.pas, exercises/ocr-numbers/uOcrNumbersTest.pas
=> ocr-numbers: add exercise to Delphi track

config.json
A core exercise has been added.  I have updated the unlocked by settings on several exercises as an exercise has been demoted form core to side.
=> update unlockedby settings

exercises/twelve-days/uTwelveDaysTests.pas
=> twelve-days: Add case sensitivity to test suite

exercises/anagram/uAnagramTests.pas
per exercism/problem-specifications#1348
=> anagram: update to v1.4.0

exercises/robot-simulator/uRobotSimulatorExample.pas, exercises/robot-simulator/uRobotSimulatorTest.pas
per exercism/problem-specifications#1343 and exercism/problem-specifications#1357
=> robot-simulator: update to v3.1.0

exercises/phone-number/uPhoneNumberTests.pas
=> phone-number: bump version to v1.6.1

exercises/triangle/uTestTriangle.pas
per exercism/problem-specifications#1352
=> Triangle: update to v1.2.0

exercises/leap/uLeapTests.pas
per exercism/problem-specifications#1359
=> leap: update to v1.4.0

exercises/sum-of-multiples/uSumOfMultiplesTest.pas, exercises/sum-of-multiples/uSumsOfMultiplesExample.pas
per exercism/problem-specifications#1362
=> sum-of-multiples: Update to v1.3.0

config.json, exercises/robot-name/README.md, exercises/robot-name/RobotName.dpr, exercises/robot-name/uRobotNameExample.pas, exercises/robot-name/uRobotNameTest.pas
There is no canonical for this exercise. I'm not sure that tests are adequate for this exercise
=> robot-name: add new exercise

exercises/sum-of-multiples/uSumOfMultiplesTest.pas
also applied changes from 1.4.1.
Waiting for exercism/problem-specifications#1373 to be merged.
=> WIP: sum-of-multiples: update to v1.5.0

exercises/acronym/uAcronymExample.pas, exercises/acronym/uAcronymTests.pas
Adds apostrophe test.
per exercism/problem-specifications#1377
=> Acronym: update exercise to v1.6.0

config.json
This may become a side exercise to Accumulate, if and when that exercise is added to the track.
=> roman-numerals: demote to unassigned side exercise

exercises/bracket-push/uBracketPushTest.pas
per exercism/problem-specifications#1392
=> bracket-push: update to v1.5.0

exercises/isogram/uIsogramTests.pas
per exercism/problem-specifications#1393
=> isogram: update to v1.7.0

exercises/luhn/uLuhnTest.pas
per exercism/problem-specifications#1394
=> Luhn: update to v1.3.0

exercises/wordy/README.md, exercises/wordy/uWordyExample.pas, exercises/wordy/uWordyTests.pas
per exercism/problem-specifications#1382 and exercism/problem-specifications#1383
=> wordy: update to v1.4.0

config.json, exercises/palindrome-products/PalindromeProducts.dpr, exercises/palindrome-products/README.md, exercises/palindrome-products/uPalindromeProducts.pas, exercises/palindrome-products/uPalindromeProductsExample.pas, exercises/palindrome-products/uPalindromeProductsTest.pas
palindrome-products: canonical version added
per exercism/problem-specifications#1152
=> palindrome-products: add new exercise

config.json
Set difficulty to 4 and add "loops" and "arrays" to "topics".
=> diamond: update entry

exercises/clock/uClockTest.pas
per exercism/problem-specifications#1400
=> clock: update to v2.4.0

exercises/binary-search/uBinarySearchTest.pas
per exercism/problem-specifications#1399
=> binary-search: update to v1.3.0

exercises/binary-search/uBinarySearchTest.pas
reduced each test to a single line.
=> binary-search: refactor tests

exercises/gigasecond/uGigasecondExample.pas, exercises/gigasecond/uGigasecondTest.pas
per exercism/problem-specifications#1405
=> Gigasecond: update to v2.0.0

exercises/wordy/uWordyExample.pas, exercises/wordy/uWordyTests.pas
per exercism/problem-specifications#1401
=> Wordy: Update to v1.5.0

exercises/leap/README.md
per exercism/problem-specifications#1418
=> Leap: update README

exercises/saddle-points/README.md, exercises/saddle-points/uSaddlePointsExample.pas, exercises/saddle-points/uSaddlePointsTests.pas
per exercism/problem-specifications#1434 and exercism/problem-specifications#1429
=> saddle-points: update to v1.5.0

exercises/acronym/uAcronymTests.pas
per exercism/problem-specifications#1436
=> Acronym: update to v1.7.0

exercises/grains/README.md
per exercism/problem-specifications#1445
=> Grains: update README

config.json, exercises/rotational-cipher/README.md, exercises/rotational-cipher/RotationalCipher.dpr, exercises/rotational-cipher/uRotationalCipherExample.pas, exercises/rotational-cipher/uRotationalCipherTests.pas
This is still being developed and is waiting on the outcome of an open PR in problem-specifications.
=> Rotational-Cipher: Add new exercise

exercises/high-scores/uHighScoresExample.pas, exercises/high-scores/uHighScoresTest.pas
per exercism/problem-specifications#1447
=> High-Scores: update to v3.0.0

exercises/resistor-color/ResistorColor.dpr, exercises/resistor-color/uResistorColorExample.pas, exercises/resistor-color/uResistorColorTests.pas
Solution file should be uResistorColor.pas instead of uResistor.pas
=> Resistor-Color: renamed solution file

config.json, exercises/parallel-letter-frequency/.meta/uParallelLetterFrequencyExample.pas, exercises/parallel-letter-frequency/ParallelLetterFrequency.dpr, exercises/parallel-letter-frequency/README.md, exercises/parallel-letter-frequency/uParallelLetterFrequency.pas, exercises/parallel-letter-frequency/uParallelLetterFrequencyTest.pas
Modeled after C# track implementation.  No canonical data exists for this exercise.
=> Parallel-Letter-Frequency: add new exercise

exercises/leap/uLeapTests.pas
per exercism/problem-specifications#1465
=> leap: update to v1.5.0

config.json
At the same time reduce difficulty.
=> circular-buffer: relocate in core sequence

exercises/triangle/uTestTriangle.pas
per exercism/problem-specifications#1483
=> Triangle: update to v1.2.1

exercises/luhn/uLuhnExample.pas, exercises/luhn/uLuhnTest.pas
per exercism/problem-specifications#1480
closes #384
=> Luhn: update to v1.5.0

exercises/darts/uDartsExample.pas, exercises/darts/uDartsTest.pas
per exercism/problem-specifications#1448 and exercism/problem-specifications#1488
=> Darts: Update to v1.2.0

config.json
Clean up format with configlet fmt command.
=> Config.json: configlet fmt .

exercises/allergies/uAllergiesExample.pas, exercises/allergies/uAllergyTests.pas
per exercism/problem-specifications#1494
=> Allergies: update to v2.0.0

exercises/darts/README.md
=> Dart: update Readme

exercises/queen-attack/uQueenAttackExample.pas, exercises/queen-attack/uQueenAttackTest.pas
per exercism/problem-specifications#1504
=> Queen-Attack: update to v2.3.0

exercises/markdown/uMarkdown.pas, exercises/markdown/uMarkdownExample.pas, exercises/markdown/uMarkdownTest.pas
per exercism/problem-specifications#1490
I would like to thank one of this tracks students, who goes by makafakachka, for going above and beyond by providing the necessary changes to the example solution to pass the added test case.
=> Markdown: Update to v1.4.0

exercises/luhn/uLuhnTest.pas
per exercism/problem-specifications#1500
=> Luhn: update to v1.6.0

exercises/bob/README.md
per exercism/problem-specifications#1516
=> Bob: update README

exercises/luhn/uLuhnTest.pas
per exercism/problem-specifications#1523
=> Luhn: update to v1.6.1

exercises/reverse-string/uReverseStringExample.pas, exercises/reverse-string/uReverseStringTests.pas
per exercism/problem-specifications#1519
=> Reverse-String: update to v1.2.0

exercises/pangram/uPangramExample.pas, exercises/pangram/uPangramTests.pas
per exercism/problem-specifications#1533
=> Pangram: update to v2.0.0

config/exercise_readme.go.tmpl
=> resolves #401

config.json
Align topics better with TOPICS.TXT.  Some topics perhaps could be added to TOPICS.TXT.
=> Update Exercise Topics

config.json
=> Configure Online Editor

config.json
resolves #422
What are the available "icon" options?  These don't appear to be documented.  For now I am essentially just borrowing what I found in csharp, similar enough.
=> Adds Key Features

exercises/practice/hello-world/GETTING_STARTED_GUIDE.md
=> Removes broken link from document

exercises/shared/.docs/tests.md
closes #479
Thanks @kotp and @NobbZ.  Hopefully this one change is enough.  A quick check didn't show any other problems.
=> Updates url

exercises/practice/sieve/.docs/instructions.md, exercises/practice/sieve/.docs/introduction.md, exercises/practice/sieve/.meta/config.json
Sync the `sieve` exercise with the latest data, as defined in https://github.com/exercism/problem-specifications/tree/main/exercises/sieve.
- Feel free to close this PR if there is another PR that also syncs this exercise.
- When approved, feel free to merge this PR yourselves (you don't have to wait for me).
As this PR only updates docs and/or metadata, it won't trigger a re-run of existing solutions (see [the docs](https://exercism.org/docs/building/tracks)).
=> sieve: sync
