exercism/delphi

- exercises/book-store/uBookStoreTests.pas
Test runner is no longer DRY and very closely matces this exercises
canonicaldata.json. As an aside I think the canonicaldata.json is too
wordy on some the tests. Test 8 gives a hint towards the solution that
I don't like. I think "targetdata" makes the description of test 8 a
little redundant in my opinion.
> [book-store] Updates test runner so it is not DRY

- SETUP.md
Since this track of "pascal" is really Delphi, we need to give
information about how to run our tests.
This provides a short reminder, which will serve if someone started the
track, but took some time off, and came back and forgets this is Delphi.
> SETUP.md for reminding about testing

- config.json
@kytrinyx agrees that the track should be renamed.   The xpascal repo will need to be renamed, guessing xdelphipascal will be the new name.
> Changes track description to Delphi Pascal

- config.json
- exercises/grains/GrainsTests.dpr
- exercises/grains/uGrainsExample.pas
- exercises/grains/uGrainsTests.pas
exercise based on C# example but updated to follow canonical-data.json for this exercise.
> grains: adding exercise to track

- SETUP.md
mark down reference to installation.md was not complete.  Updated to point to http://www.exercism.io/languages/delphi/installing.  This file is appended to readme.md that is delievered with each assignment to  the student.
> added missing url reference

- exercises/bob/Bob.dpr
This will prevent the DPR from appearing as part of the test suite on the site to the student.  The file is still delivered when fetched with client.
> bob: rename DPR to remove test from name

- exercises/bob/uBobTests.pas
`[Ignore]` fields updated to read as `[Ignore('Comment this line to run this test')]` to be more informative to the student, especially since this is a very early exercise in this track.
> bob: adds instruction to [Ignore] properties

- docs/TESTS.md
Fixed an instance of bad spelling.  Added a link to the command line client download page.
> readme.md: correct typos, add link to command line client

- exercises/phone-number/uPhoneNumberExample.pas
- exercises/phone-number/uPhoneNumberTests.pas
Canonical-data.json recently changed.  Updating test runner and example solution to align with new json.
> phone-number: update to match canonical-data.json

- exercises/phone-number/uPhoneNumberExample.pas
- exercises/phone-number/uPhoneNumberTests.pas
related to PR https://github.com/exercism/x-common/pull/745
> phone-number: sync with updated canonical-data.json

- config.json
- exercises/two-fer/twofer.dpr
- exercises/two-fer/utwoferExample.pas
- exercises/two-fer/utwoferTest.pas
A new exercise that has been designed as a replacement to the original hello-world exercise.  Two-fer is intended to be a follow on exercise to the new hello-world exercise.
> Add exercise two-fer

- SETUP.md
> setup.md: grammar improvement

- exercises/bank-account/uBankAccountTests.pas
If an exception is raised with in the execution of a thread we need that thread to decrement the active thread count and have the allthreadsDone event to be set regardless of how a thread terminates.  UpdateBalance will raise an exception if the bank account is not open.
> bank-account: guard against exceptions

- config/exercise_readme.go.tmpl
- exercises/allergies/README.md
- exercises/bank-account/README.md
- exercises/beer-song/README.md
- exercises/binary-search/README.md
- exercises/bob/README.md
- exercises/book-store/README.md
- exercises/bowling/README.md
- exercises/circular-buffer/README.md
- exercises/clock/README.md
- exercises/collatz-conjecture/README.md
- exercises/etl/README.md
- exercises/grains/README.md
- exercises/hamming/README.md
- exercises/hello-world/README.md
- exercises/leap/README.md
- exercises/minesweeper/README.md
- exercises/nucleotide-count/README.md
- exercises/perfect-numbers/README.md
- exercises/phone-number/README.md
- exercises/poker/README.md
- exercises/raindrops/README.md
- exercises/rna-transcription/README.md
- exercises/roman-numerals/README.md
- exercises/saddle-points/README.md
- exercises/triangle/README.md
- exercises/two-fer/README.md
- exercises/wordy/README.md
We are working towards making exercises stand-alone. That is to say: no more generating READMEs on the fly.
This will give maintainers more control over each individual exercise README, and it will also make some of the backend logic for delivering exercises simpler.
The README template uses the Go text/template package, and the default templates generate the same READMEs as we have been generating on the fly.  See the documentation in [regenerating exercise readmes][regenerate-docs] for details.
The READMEs can be generated at any time using a new 'generate' command in configlet. This command has not yet landed in master or been released, but can be built from source in the generate-readmes branch on [configlet][].
[configlet]: https://github.com/exercism/configlet
[regenerate-docs]: …
> Generate static exercise README templates

- config.json
> Changes based on instructions from PR #135

- config.json
`configlet lint .` passed all these UUIDs.
> implement unique UUIDs for each exercise.

- config.json
The previous version of `configlet uuid` was known to generate invalid UUIDs. The latest release of Configlet [v3.6.1](https://github.com/exercism/configlet/releases) fixes that issue for newly added exercises, but existing exercise UUIDs need to be updated manually.
This change pertains to exercism/configlet#99
> Fix invalid exercise UUIds

- exercises/bob/README.md
- exercises/bob/uBobExample.pas
- exercises/bob/uBobTests.pas
Updated test suite and example solution to conform to v1.1.0 of test data.
> bob: update to v1.1.0

- config.json
- exercises/armstrong-numbers/ArmstrongNumbers.dpr
- exercises/armstrong-numbers/README.md
- exercises/armstrong-numbers/uArmstrongNumbersExample.pas
- exercises/armstrong-numbers/uArmstrongNumbersTests.pas
Implementing Armstrong numbers exercise from PR exercism/problem-specifications#1018
> armstrong-numbers: New exercise

- exercises/rna-transcription/uTestRnaTranscription.pas
Checks for invalid input removed per exercism/problem-specifications#1027
> rna-transcription: update to v1.1.0

- docs/INSTALLATION.md
`u` needs to be `U` in one spot.
> installation.md: correct minor typo

- exercises/isbn-verifier/uTestISBNVerifier.pas
per exercism/problem-specifications#1055
> isbn-verifier: add new test case

- exercises/phone-number/uPhoneNumberTests.pas
ToString is a method of ancestor class TObject.  Each student can override the method with there own, but overridding ancestor methods isn't really in the scope of this exercise, and this particular case is a bonus.
> phone-number: rename ToString to Formatted

- exercises/clock/uClockTest.pas
several descriptions in the TESTDATA differed from the test suite.  Corrected
> clock: correct spelling errors

- config.json
fixes #219
#219 indicates that `isbn-verifier` is being unlocked by a non-core exercise, `bob`.  This PR re-designates `bob` to be a core exercise, which will correct the conflict.
> track config: bob is now a core exercise

- docs/ABOUT.md
About.md now follows formatting guidelines described in #234.
> reformat About to be V2 compliant

- docs/INSTALLATION.md
Delphi Starter Edition (SE) has been replaced with Community Edition (CE).  CE is still free, but is not crippled like SE was.  All of the capabilities of Professional version of Delphi are available.
> update Delphi and DUnitX installation instructions

- config.json
- exercises/pascals-triangle/PascalsTriangle.dpr
- exercises/pascals-triangle/README.md
- exercises/pascals-triangle/uPascalsTriangleExample.pas
- exercises/pascals-triangle/uPascalsTriangleTest.pas
> Pascals-triangle: add exercise

- config.json
Demoted `circular-buffer` to a side exercise.
`Bowling` now unlocked by `markdown` instead of unlocked by `circular-buffer`.
> reassignment of exercises in configuration

- exercises/hamming/uHammingTests.pas
per exercism/problem-specifications#1412
> Hamming: Update to v2.2.0

- exercises/luhn/uLuhnTest.pas
per exercism/problem-specifications#1420
> Luhn: Update to v1.4.0

- exercises/matrix/README.md
- exercises/matrix/uMatrixExample.pas
- exercises/matrix/uMatrixTest.pas
per exercism/problem-specifications#1387
> Matrix: update to v1.1.0

- config.json
Cores moved to top of the list.  Some exercises promoted to core and some resigned to be side exercises.
The new tree appears as so:
core
----
```
├─ hello-world
│  ├─ hamming
│  ├─ pangram
│  └─ robot-name
│
├─ two-fer
│  ├─ acronym
│  └─ isogram
│
├─ leap
│  ├─ grains
│  └─ perfect-numbers
│
├─ gigasecond
│  ├─ collatz-conjecture
│  ├─ phone-number
│  ├─ scrabble-score
│  └─ meetup
│
├─ series
│  ├─ sum-of-multiples
│  ├─ difference-of-squares
│  ├─ high-scores
│  ├─ all-your-base
│  ├─ pascals-triangle
│  ├─ protein-translation
│  ├─ secret-handshake
│  ├─ prime-factors
│  └─ roman-numerals
│
├─ space-age
│  ├─ armstrong-numbers
│  ├─ triangle
│  └─ darts
│
├─ raindrops
│  ├─ beer-song
│  ├─ sieve
│  └─ proverb
│
├─ bob
│  ├─ isbn-verifier
│  ├─ twelve-days
│  ├─ anagram
│  ├─ …
```
> config.json: re-sort exercises

- exercises/hamming/uHammingExample.pas
- exercises/hamming/uHammingTests.pas
per exercism/problem-specifications#1450
> Hamming: update to v2.3.0

- exercises/high-scores/README.md
- exercises/high-scores/uHighScoresTest.pas
Canonical data opted to remove Report cases.  I have preserved them and have flagged them as optional bonus test cases.
per exercism/problem-specifications#1459
> high-scores: update to v4.0.0

- config.json
- exercises/resistor-color/README.md
- exercises/resistor-color/ResistorColor.dpr
- exercises/resistor-color/uResistorColorTests.pas
- exercises/resistor-color/uResistorExample.pas
per exercism/problem-specifications#1457
> Resistor-Color: new exercise

- config.json
- exercises/high-scores/.meta/hints.md
- exercises/high-scores/uHighScoresExample.pas
- exercises/high-scores/uHighScoresTest.pas
The exercise was not really utilizing lists.  That has been corrected.
> high-scores: revamped implementation to closely match topic

- exercises/high-scores/uHighScoresTest.pas
I had some transposed data from original canonical data.
> high-scores: fix bogus bonus test cases

- docs/ABOUT.md
- docs/INSTALLATION.md
- docs/LEARNING.md
- docs/RESOURCES.md
- docs/TESTS.md
- exercises/practice/hello-world/GETTING_STARTED_GUIDE.md
- exercises/practice/high-scores/.docs/instructions.append.md
- exercises/practice/rational-numbers/.docs/instructions.append.md
- exercises/practice/twelve-days/.docs/instructions.append.md
We've defined a [specification for Markdown files](https://github.com/exercism/docs/blob/main/contributing/standards/markdown.md) to be applied Exercism-wide. This standard includes, amongst others, the following two rules:
- All files must start start with a level-1 heading (`# Some heading text`)
- No heading may decend a level greater than one below the previous (e.g. `## may only be followed by ###, not ####`)
This PR applies the above two rules to the Markdown documents in this repo. 
https://github.com/exercism/v3-launch/issues/17
> [v3] Update Markdown files to latest spec

- exercises/practice/hello-world/uHelloWorld.pas
Simplify the `hello-world` exercise's stub. The goal of this is to make things easier for students to get started and to introduce as little syntax as possible.
See https://github.com/exercism/v3-launch/issues/46
> 🤖 Simplify `hello-world` stub
